# Site
repository: haquemdanamul/haquemdanamul.github.io
# favicon: images/favicon.ico

# Personal info
name: Dr. Mohammad Anamul Haque 
title: Faculty member, Shahjalal University of Science & Technology, Bangladesh
email: mohammadanamul.haque@studenti.unipd.it; haque-sta@sust.edu

# Social links
facebook_username: Mohammadanamul.haque.908
github_username:  haquemdanamul
linkedin_username: linkedin.com/in/mohammad-anamul-haque-phd-40541060
researchgate_username: Mohammad_Anamul_Haque
orcid_id: cid.org/0000-0003-4461-1594

# About Section
# about_title: About Me
about_profile_image: images/mee.jpg
about_content: | # this will include new lines to allow paragraphs
  I am nobody
