# Site
repository: haquemdanamul/haquemdanamul.github.io
# favicon: images/favicon.ico

# Personal info
name: Mohammad Anamul HAque
title: PhD student in Statistics, University of Padua
email: mohammadanamul.haque@studenti.unipd.it

# Social links
facebook_username: Mohammadanamul.haque.908
github_username:  haquemdanamul
linkedin_username: mohammad-anamul-haque-40541060
researchgate_username: Mohammad_Anamul_Haque

# About Section
# about_title: About Me
about_profile_image: images/mee.jpg
about_content: | # this will include new lines to allow paragraphs
  I am nobody
